install.packages(c("car", "mapview", "spatialreg"))
library(tidyverse)
library(tmap)
library(geojsonio)
library(plotly)
library(rgdal)
library(broom)
library(mapview)
library(crosstalk)
library(sf)
library(sp)
library(spdep)
library(car)
LondonBoroughsss <- readOGR("N:/ddL/statistical-gis-boundaries-london/ESRI/London_Borough_Excluding_MHW.shp", layer="London_Borough_Excluding_MHW")
LondonBoroughsssSF <- st_as_sf(LondonBoroughsss)
LondonBoroughsssSF
BNG = "+init=epsg:27700"
LondonBoroughsssSFBNG <- st_transform(LondonBoroughsssSF, BNG)
qtm(LondonBoroughsssSFBNG)
LondonBoroughProfiles <- read_csv("N:/The Night-time Economy/Data/data.csv")
LonBoroughProfiles <- left_join(LondonBoroughsssSFBNG, LondonBoroughProfiles, by = c("GSS_CODE" = "Area code"))
boxplot(LonBoroughProfiles$`Night Time Economy 2017`, main="Night Time Economy 2017")
boxplot(LonBoroughProfiles$`Pubs units 2017`, main="Pubs units 2017")
boxplot(LonBoroughProfiles$`Small pubs units 2017`, main="Small pubs units 2017")
boxplot(LonBoroughProfiles$`Licensed Restaurant units 2017`, main="Licensed Restaurant units 2017")
boxplot(LonBoroughProfiles$`Unlicensed Restaurant and Cafe units 2017`, main="Unlicensed Restaurant and Cafe units 2017")
boxplot(LonBoroughProfiles$`Takeaway Food Shops and Mobile Food Stand units 2017`, main="Takeaway Food Shops and Mobile Food Stand units 2017")
boxplot(LonBoroughProfiles$`Licensed Club units 2017`, main="Licensed Club units 2017")
newLonBoroughProfiles <- LonBoroughProfiles[-c(25,26),]
tmap_mode("view")
qtm(LonBoroughProfiles, fill = "Night Time Economy 2017", borders = NULL)
tmap_mode("view")
qtm(newLonBoroughProfiles, fill = "Night Time Economy 2017", borders = NULL)
q <- qplot(x = `Pubs units 2017`, y = `Night Time Economy 2017`, data=newLonBoroughProfiles)
q + stat_smooth(method="lm", se=FALSE, size=1) + geom_jitter()
q <- qplot(x = `Small pubs units 2017`, y = `Night Time Economy 2017`, data=newLonBoroughProfiles)
q + stat_smooth(method="lm", se=FALSE, size=1) + geom_jitter()
q <- qplot(x = `Licensed Restaurant units 2017`, y = `Night Time Economy 2017`, data=newLonBoroughProfiles)
q + stat_smooth(method="lm", se=FALSE, size=1) + geom_jitter()
q <- qplot(x = `Unlicensed Restaurant and Cafe units 2017`, y = `Night Time Economy 2017`, data=newLonBoroughProfiles)
q + stat_smooth(method="lm", se=FALSE, size=1) + geom_jitter()
q <- qplot(x = `Takeaway Food Shops and Mobile Food Stand units 2017`, y = `Night Time Economy 2017`, data=newLonBoroughProfiles)
q + stat_smooth(method="lm", se=FALSE, size=1) + geom_jitter()
q <- qplot(x = `Licensed Club units 2017`, y = `Night Time Economy 2017`, data=newLonBoroughProfiles)
q + stat_smooth(method="lm", se=FALSE, size=1) + geom_jitter()
model1 <- lm(`Night Time Economy 2017` ~ `Pubs units 2017`+`Small pubs units 2017`+`Licensed Restaurant units 2017`+`Unlicensed Restaurant and Cafe units 2017`+`Takeaway Food Shops and Mobile Food Stand units 2017`+`Licensed Club units 2017`, data = newLonBoroughProfiles)
summary(model1)
newLonBoroughProfiles$model1_resids <- model1$residuals
qplot(model1$residuals) + geom_histogram()
vif(model1)
plot(model1)
durbinWatsonTest(model1)
tmap_mode("view")
newLonBoroughProfilesSP <- as(newLonBoroughProfiles,"Spatial")
names(newLonBoroughProfilesSP)
coordsW <- coordinates(newLonBoroughProfilesSP)
plot(coordsW)
LBorough_nb <- poly2nb(newLonBoroughProfilesSP, queen=T)
knn_Borough <- knearneigh(coordsW, k=4)
LBorough_knn <- knn2nb(knn_Borough)
plot(LBorough_nb, coordinates(coordsW), col="red")
plot(LBorough_knn, coordinates(coordsW), col="blue")
plot(newLonBoroughProfilesSP)
LBorough.queens_weight <- nb2listw(LBorough_nb, style="C")
LBorough.knn_4_weight <- nb2listw(LBorough_knn, style="C")
moran.test(newLonBoroughProfilesSP@data$model1_resids, LBorough.queens_weight)
moran.test(newLonBoroughProfilesSP@data$model1_resids, LBorough.knn_4_weight)
library(spatialreg)
slag_dv_model1_queen <- lagsarlm(`Night Time Economy 2017` ~ `Pubs units 2017`+`Small pubs units 2017`+`Licensed Restaurant units 2017`+`Unlicensed Restaurant and Cafe units 2017`+`Takeaway Food Shops and Mobile Food Stand units 2017`+`Licensed Club units 2017`, data = newLonBoroughProfiles, nb2listw(LBorough_nb, style="C"), method = "eigen")
summary(slag_dv_model1_queen)
slag_dv_model1_knn4 <- lagsarlm(`Night Time Economy 2017` ~ `Pubs units 2017`+`Small pubs units 2017`+`Licensed Restaurant units 2017`+`Unlicensed Restaurant and Cafe units 2017`+`Takeaway Food Shops and Mobile Food Stand units 2017`+`Licensed Club units 2017`, data = newLonBoroughProfiles, nb2listw(LBorough_knn, style="C"), method = "eigen")
summary(slag_dv_model1_knn4)
newLonBoroughProfilesSP@data$slag_dv_model1_knn_resids <- slag_dv_model1_knn4$residuals
moran.test(newLonBoroughProfilesSP@data$slag_dv_model1_knn_resids, LBorough.knn_4_weight)
newLonBoroughProfilesSP@data$slag_dv_model1_queen_resids <- slag_dv_model1_queen$residuals
moran.test(newLonBoroughProfilesSP@data$slag_dv_model1_queen_resids, LBorough.queens_weight)
sem_model1 <- errorsarlm(`Night Time Economy 2017` ~ `Pubs units 2017`+`Small pubs units 2017`+`Licensed Restaurant units 2017`+`Unlicensed Restaurant and Cafe units 2017`+`Takeaway Food Shops and Mobile Food Stand units 2017`+`Licensed Club units 2017`, data = newLonBoroughProfiles, nb2listw(LBorough_knn, style="C"), method = "eigen")
summary(sem_model1)
sem_model2 <- errorsarlm(`Night Time Economy 2017` ~ `Pubs units 2017`+`Small pubs units 2017`+`Licensed Restaurant units 2017`+`Unlicensed Restaurant and Cafe units 2017`+`Takeaway Food Shops and Mobile Food Stand units 2017`+`Licensed Club units 2017`, data = newLonBoroughProfiles, nb2listw(LBorough_nb, style="C"), method = "eigen")
summary(sem_model2)
qtm(newLonBoroughProfiles, fill="model1_resids")